
# import sqlite3
 

# conn = sqlite3.connect('test.db')

# conn.execute("INSERT INTO TwitterPOST4 (USER,POSTURL) \
#       VALUES ('developer@ctgroup.in','https://twitter.com/CTGroupshahpur/status/1535112631727448069' )")
# conn.execute("INSERT INTO TwitterPOST (USER,POSTURL) \
#       VALUES ('developer@ctgroup.in','https://twitter.com/CTGroupshahpur/status/1535112631727448060' )")

# conn.commit()
# print("Records created successfully")
# conn.close()